"""fresh schema

Revision ID: 20260505_0001
Revises: 
Create Date: 2026-05-05 12:35:43.913240
"""
from alembic import op
import sqlalchemy as sa



revision = '20260505_0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_sandbox_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('memory_usage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_sandbox_logs_id'), 'ai_sandbox_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_sandbox_logs_plugin_id'), 'ai_sandbox_logs', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_ai_sandbox_logs_task_id'), 'ai_sandbox_logs', ['task_id'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('jwt_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.String(length=32), nullable=False),
    sa.Column('secret_key', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jwt_keys_id'), 'jwt_keys', ['id'], unique=False)
    op.create_index(op.f('ix_jwt_keys_key_id'), 'jwt_keys', ['key_id'], unique=True)
    op.create_table('permission_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('group_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['permission_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_groups_code'), 'permission_groups', ['code'], unique=True)
    op.create_index(op.f('ix_permission_groups_id'), 'permission_groups', ['id'], unique=False)
    op.create_index(op.f('ix_permission_groups_parent_id'), 'permission_groups', ['parent_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_category'), 'permissions', ['category'], unique=False)
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('server_key_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('private_key_encrypted', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_server_key_pairs_id'), 'server_key_pairs', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('group', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_group'), 'system_settings', ['group'], unique=False)
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_index(op.f('ix_zones_slug'), 'zones', ['slug'], unique=True)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_email'), 'email_verification_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_id'), 'email_verification_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('target_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('permission_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_audit_logs_id'), 'permission_audit_logs', ['id'], unique=False)
    op.create_table('permission_group_inheritance',
    sa.Column('parent_group_id', sa.Integer(), nullable=False),
    sa.Column('child_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_group_id'], ['permission_groups.id'], ),
    sa.ForeignKeyConstraint(['parent_group_id'], ['permission_groups.id'], ),
    sa.PrimaryKeyConstraint('parent_group_id', 'child_group_id')
    )
    op.create_table('permission_group_items',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['permission_groups.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'permission_id')
    )
    op.create_table('plugins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=255), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('repo_url', sa.String(length=500), nullable=True),
    sa.Column('repo_branch', sa.String(length=100), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('readme', sa.Text(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('rating_average', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('APPROVED', 'DISABLED', name='pluginstatus'), nullable=True),
    sa.Column('is_featured', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugins_id'), 'plugins', ['id'], unique=False)
    op.create_index(op.f('ix_plugins_name'), 'plugins', ['name'], unique=False)
    op.create_index(op.f('ix_plugins_slug'), 'plugins', ['slug'], unique=True)
    op.create_table('user_permission_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['permission_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('plugin_categories',
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ),
    sa.PrimaryKeyConstraint('plugin_id', 'category_id')
    )
    op.create_table('plugin_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('rating_type', sa.String(length=20), nullable=False),
    sa.Column('functionality', sa.Enum('S', 'A', 'B', 'C', 'D', name='ratinggrade'), nullable=True),
    sa.Column('security', sa.Enum('S', 'A', 'B', 'C', 'D', name='ratinggrade'), nullable=True),
    sa.Column('documentation', sa.Enum('S', 'A', 'B', 'C', 'D', name='ratinggrade'), nullable=True),
    sa.Column('rated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_ratings_id'), 'plugin_ratings', ['id'], unique=False)
    op.create_table('plugin_signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('files_hash', sa.String(length=32), nullable=False),
    sa.Column('files_md5', sa.JSON(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('plugin_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('keypair_id', sa.Integer(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['keypair_id'], ['server_key_pairs.id'], ),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_signatures_id'), 'plugin_signatures', ['id'], unique=False)
    op.create_table('plugin_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'IN_REVIEW', 'CLOSED', name='submissionstatus'), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'CANCELED', 'SUPERSEDED', name='reviewdecision'), nullable=True),
    sa.Column('current_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('current_review_case_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_review_case_id'], ['plugin_review_cases.id'], name='fk_plugin_submissions_current_review_case_id', use_alter=True),
    sa.ForeignKeyConstraint(['current_snapshot_id'], ['plugin_submission_snapshots.id'], name='fk_plugin_submissions_current_snapshot_id', use_alter=True),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_submissions_author_id'), 'plugin_submissions', ['author_id'], unique=False)
    op.create_index(op.f('ix_plugin_submissions_decision'), 'plugin_submissions', ['decision'], unique=False)
    op.create_index(op.f('ix_plugin_submissions_id'), 'plugin_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_plugin_submissions_plugin_id'), 'plugin_submissions', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_plugin_submissions_status'), 'plugin_submissions', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plugin_id', 'author_id', name='unique_user_plugin_review')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_table('versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('source_repo_url', sa.String(length=500), nullable=True),
    sa.Column('source_commit', sa.String(length=64), nullable=True),
    sa.Column('release_tag', sa.String(length=100), nullable=True),
    sa.Column('release_url', sa.String(length=500), nullable=True),
    sa.Column('actions_run_url', sa.String(length=500), nullable=True),
    sa.Column('package_url', sa.String(length=500), nullable=True),
    sa.Column('package_sha256', sa.String(length=64), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('neko_repo', sa.String(length=200), nullable=True),
    sa.Column('neko_ref', sa.String(length=100), nullable=True),
    sa.Column('neko_commit', sa.String(length=64), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verification_summary', sa.Text(), nullable=True),
    sa.Column('min_app_version', sa.String(length=20), nullable=True),
    sa.Column('max_app_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versions_id'), 'versions', ['id'], unique=False)
    op.create_table('plugin_submission_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('repo_owner', sa.String(length=120), nullable=True),
    sa.Column('repo_name', sa.String(length=160), nullable=True),
    sa.Column('submitted_ref', sa.String(length=120), nullable=True),
    sa.Column('resolved_commit', sa.String(length=64), nullable=True),
    sa.Column('commit_url', sa.String(length=500), nullable=True),
    sa.Column('actions_run_url', sa.String(length=500), nullable=True),
    sa.Column('artifact_url', sa.String(length=500), nullable=True),
    sa.Column('license_name', sa.String(length=100), nullable=True),
    sa.Column('plugin_name', sa.String(length=100), nullable=False),
    sa.Column('plugin_slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=255), nullable=True),
    sa.Column('zone_slug', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['plugin_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_submission_snapshots_id'), 'plugin_submission_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_plugin_submission_snapshots_submission_id'), 'plugin_submission_snapshots', ['submission_id'], unique=False)
    op.create_table('plugin_review_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='reviewcasestatus'), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'CANCELED', 'SUPERSEDED', name='reviewdecision'), nullable=True),
    sa.Column('opened_by', sa.Integer(), nullable=True),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('decision_summary', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['plugin_submission_snapshots.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['plugin_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_review_cases_decision'), 'plugin_review_cases', ['decision'], unique=False)
    op.create_index(op.f('ix_plugin_review_cases_id'), 'plugin_review_cases', ['id'], unique=False)
    op.create_index(op.f('ix_plugin_review_cases_snapshot_id'), 'plugin_review_cases', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_plugin_review_cases_status'), 'plugin_review_cases', ['status'], unique=False)
    op.create_index(op.f('ix_plugin_review_cases_submission_id'), 'plugin_review_cases', ['submission_id'], unique=False)
    op.create_table('plugin_review_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'MAJOR', 'MINOR', 'NITPICK', name='reviewcommentseverity'), nullable=False),
    sa.Column('target_area', sa.Enum('OWNERSHIP', 'METADATA', 'CODE', 'SECURITY', 'PACKAGING', 'LICENSE', 'DOCS', 'RELEASE', 'OTHER', name='reviewtargetarea'), nullable=False),
    sa.Column('target_ref', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['plugin_review_cases.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_review_comments_author_id'), 'plugin_review_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_plugin_review_comments_case_id'), 'plugin_review_comments', ['case_id'], unique=False)
    op.create_index(op.f('ix_plugin_review_comments_id'), 'plugin_review_comments', ['id'], unique=False)
    op.create_index(op.f('ix_plugin_review_comments_is_resolved'), 'plugin_review_comments', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_plugin_review_comments_severity'), 'plugin_review_comments', ['severity'], unique=False)
    op.create_index(op.f('ix_plugin_review_comments_target_area'), 'plugin_review_comments', ['target_area'], unique=False)
    op.create_table('plugin_review_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('DRAFT_CREATED', 'DRAFT_UPDATED', 'SUBMITTED', 'REVIEW_STARTED', 'COMMENTED', 'COMMENT_UPDATED', 'COMMENT_RESOLVED', 'COMMENT_REOPENED', 'APPROVED', 'REJECTED', 'CLOSED', 'REOPENED', 'WITHDRAWN', name='revieweventtype'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['plugin_review_cases.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['plugin_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_review_events_actor_id'), 'plugin_review_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_plugin_review_events_case_id'), 'plugin_review_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_plugin_review_events_event_type'), 'plugin_review_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_plugin_review_events_id'), 'plugin_review_events', ['id'], unique=False)
    op.create_index(op.f('ix_plugin_review_events_submission_id'), 'plugin_review_events', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plugin_review_events_submission_id'), table_name='plugin_review_events')
    op.drop_index(op.f('ix_plugin_review_events_id'), table_name='plugin_review_events')
    op.drop_index(op.f('ix_plugin_review_events_event_type'), table_name='plugin_review_events')
    op.drop_index(op.f('ix_plugin_review_events_case_id'), table_name='plugin_review_events')
    op.drop_index(op.f('ix_plugin_review_events_actor_id'), table_name='plugin_review_events')
    op.drop_table('plugin_review_events')
    op.drop_index(op.f('ix_plugin_review_comments_target_area'), table_name='plugin_review_comments')
    op.drop_index(op.f('ix_plugin_review_comments_severity'), table_name='plugin_review_comments')
    op.drop_index(op.f('ix_plugin_review_comments_is_resolved'), table_name='plugin_review_comments')
    op.drop_index(op.f('ix_plugin_review_comments_id'), table_name='plugin_review_comments')
    op.drop_index(op.f('ix_plugin_review_comments_case_id'), table_name='plugin_review_comments')
    op.drop_index(op.f('ix_plugin_review_comments_author_id'), table_name='plugin_review_comments')
    op.drop_table('plugin_review_comments')
    op.drop_index(op.f('ix_plugin_review_cases_submission_id'), table_name='plugin_review_cases')
    op.drop_index(op.f('ix_plugin_review_cases_status'), table_name='plugin_review_cases')
    op.drop_index(op.f('ix_plugin_review_cases_snapshot_id'), table_name='plugin_review_cases')
    op.drop_index(op.f('ix_plugin_review_cases_id'), table_name='plugin_review_cases')
    op.drop_index(op.f('ix_plugin_review_cases_decision'), table_name='plugin_review_cases')
    op.drop_table('plugin_review_cases')
    op.drop_index(op.f('ix_plugin_submission_snapshots_submission_id'), table_name='plugin_submission_snapshots')
    op.drop_index(op.f('ix_plugin_submission_snapshots_id'), table_name='plugin_submission_snapshots')
    op.drop_table('plugin_submission_snapshots')
    op.drop_index(op.f('ix_versions_id'), table_name='versions')
    op.drop_table('versions')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_plugin_submissions_status'), table_name='plugin_submissions')
    op.drop_index(op.f('ix_plugin_submissions_plugin_id'), table_name='plugin_submissions')
    op.drop_index(op.f('ix_plugin_submissions_id'), table_name='plugin_submissions')
    op.drop_index(op.f('ix_plugin_submissions_decision'), table_name='plugin_submissions')
    op.drop_index(op.f('ix_plugin_submissions_author_id'), table_name='plugin_submissions')
    op.drop_table('plugin_submissions')
    op.drop_index(op.f('ix_plugin_signatures_id'), table_name='plugin_signatures')
    op.drop_table('plugin_signatures')
    op.drop_index(op.f('ix_plugin_ratings_id'), table_name='plugin_ratings')
    op.drop_table('plugin_ratings')
    op.drop_table('plugin_categories')
    op.drop_table('user_permission_groups')
    op.drop_index(op.f('ix_plugins_slug'), table_name='plugins')
    op.drop_index(op.f('ix_plugins_name'), table_name='plugins')
    op.drop_index(op.f('ix_plugins_id'), table_name='plugins')
    op.drop_table('plugins')
    op.drop_table('permission_group_items')
    op.drop_table('permission_group_inheritance')
    op.drop_index(op.f('ix_permission_audit_logs_id'), table_name='permission_audit_logs')
    op.drop_table('permission_audit_logs')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_email'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_zones_slug'), table_name='zones')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_group'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_server_key_pairs_id'), table_name='server_key_pairs')
    op.drop_table('server_key_pairs')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_category'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_permission_groups_parent_id'), table_name='permission_groups')
    op.drop_index(op.f('ix_permission_groups_id'), table_name='permission_groups')
    op.drop_index(op.f('ix_permission_groups_code'), table_name='permission_groups')
    op.drop_table('permission_groups')
    op.drop_index(op.f('ix_jwt_keys_key_id'), table_name='jwt_keys')
    op.drop_index(op.f('ix_jwt_keys_id'), table_name='jwt_keys')
    op.drop_table('jwt_keys')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_ai_sandbox_logs_task_id'), table_name='ai_sandbox_logs')
    op.drop_index(op.f('ix_ai_sandbox_logs_plugin_id'), table_name='ai_sandbox_logs')
    op.drop_index(op.f('ix_ai_sandbox_logs_id'), table_name='ai_sandbox_logs')
    op.drop_table('ai_sandbox_logs')
    # ### end Alembic commands ###
